name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get API FQDN from Container Apps
        id: getapi
        run: |
          API_FQDN=$(az containerapp show \
            -g "${{ secrets.AZ_RESOURCE_GROUP }}" \
            -n "${{ secrets.AZ_CONTAINER_APP_NAME }}" \
            --query "properties.configuration.ingress.fqdn" -o tsv)
          if [ -z "$API_FQDN" ]; then
            echo "Failed to fetch API FQDN"; exit 1
          fi
          echo "API_BASE_URL=https://${API_FQDN}" >> $GITHUB_ENV
          echo "Resolved API: https://${API_FQDN}"
      - name: Write runtime config.json
        run: |
          mkdir -p src/assets
          cat > src/assets/config.json <<EOF
          { "apiBaseUrl": "${{ env.API_BASE_URL }}" }
          EOF

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_SAND_056C53F0F }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/GS_dashboard/browser" # Built app content directory - optional
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"


